from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from app.models.agent import Agent
from app.models.chat import Chat
from app.models.message import Message
from app.models.user import User


class ChatService:
    @staticmethod
    def create_chat(db: Session, current_user: User, agent: Agent, title: str) -> Chat:
        chat = Chat(user_id=current_user.id, agent_id=agent.id, title=title)
        db.add(chat)
        db.commit()
        db.refresh(chat)
        return chat

    @staticmethod
    def add_user_message(db: Session, chat: Chat, current_user: User, content: str) -> Message:
        message = Message(chat_id=chat.id, user_id=current_user.id, role="user", content=content)
        db.add(message)
        db.commit()
        db.refresh(message)
        return message

    @staticmethod
    def add_agent_reply(db: Session, chat: Chat, agent: Agent, prompt: str) -> Message:
        source_label = "Local agent" if agent.source_type == "local" else "External API agent"
        behavior = agent.behavior_prompt or "Provide concise, helpful replies."
        content = (
            f"{source_label} '{agent.name}' received: {prompt}\n\n"
            f"Configured behavior: {behavior}\n"
            f"This is a demo response generated by the platform scaffold."
        )
        message = Message(chat_id=chat.id, role="assistant", content=content)
        db.add(message)
        db.commit()
        db.refresh(message)
        return message

    @staticmethod
    def ensure_chat_access(chat: Chat | None, current_user: User) -> Chat:
        if not chat or chat.user_id != current_user.id:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Chat not found")
        return chat
